import type { Game } from "./types";
export const demoGames: Game[] = [
 {id:"1",slug:"ghostrunner-2",title:"Ghostrunner 2",store:"Epic Games",description:"Ação cyberpunk em primeira pessoa com combates velozes e parkour de alta precisão.",image_url:"https://images.igdb.com/igdb/image/upload/t_1080p/co6kq7.jpg",claim_url:"https://store.epicgames.com/",original_price:179.9,starts_at:"2026-08-06T15:00:00Z",ends_at:"2026-08-13T15:00:00Z",genres:["Ação","Cyberpunk"],featured:true},
 {id:"2",slug:"breathedge",title:"Breathedge",store:"Steam",description:"Sobreviva no espaço, construa equipamentos e desvende um acidente cósmico nada convencional.",image_url:"https://cdn.akamai.steamstatic.com/steam/apps/738520/header.jpg",claim_url:"https://store.steampowered.com/app/738520/Breathedge/",original_price:74.99,starts_at:"2026-08-07T10:00:00Z",ends_at:"2026-08-10T17:00:00Z",genres:["Sobrevivência","Aventura"],featured:false},
 {id:"3",slug:"dishonored",title:"Dishonored",store:"GOG",description:"Escolha seu caminho em uma aventura de ação furtiva, poderes sobrenaturais e consequências.",image_url:"https://images.igdb.com/igdb/image/upload/t_1080p/co1r7n.jpg",claim_url:"https://www.gog.com/",original_price:59.99,starts_at:"2026-08-05T12:00:00Z",ends_at:"2026-08-15T12:00:00Z",genres:["Furtividade","RPG"],featured:false},
 {id:"4",slug:"loop-hero",title:"Loop Hero",store:"Prime Gaming",description:"Reconstrua o mundo em loops estratégicos com cartas, equipamentos e decisões difíceis.",image_url:"https://images.igdb.com/igdb/image/upload/t_1080p/co2w9a.jpg",claim_url:"https://gaming.amazon.com/",original_price:46.99,starts_at:"2026-08-01T12:00:00Z",ends_at:"2026-08-31T23:59:00Z",genres:["Estratégia","Roguelike"],featured:false}
];
export function hoursLeft(end:string, now=Date.now()){ return Math.max(0,Math.ceil((new Date(end).getTime()-now)/36e5)); }
export function money(value:number){ return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value); }
