import "server-only";
import webpush from "web-push";
import { createClient } from "@supabase/supabase-js";
import type { Game } from "./types";

function serverDb(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,secret=process.env.SYNC_SECRET;if(!url||!key||!secret)throw new Error("Configuração do servidor incompleta");return createClient(url,key,{global:{headers:{"x-sync-secret":secret}},auth:{persistSession:false}})}
function configure(){const publicKey=process.env.VAPID_PUBLIC_KEY,privateKey=process.env.VAPID_PRIVATE_KEY;if(!publicKey||!privateKey)throw new Error("Chaves Web Push ausentes");webpush.setVapidDetails("mailto:triobrabogamesdrop@gmail.com",publicKey,privateKey)}
const platformSlug=(store:string)=>store.toLowerCase().replace(/\s*\/\s*/g,"-").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").replace("epic-games","epic-games").replace("prime-gaming","prime-gaming");
export async function sendPush(game:Game){configure();const db=serverDb();const slug=platformSlug(game.store);const {data,error}=await db.from("push_subscriptions").select("id,endpoint,p256dh,auth,platforms").eq("active",true).contains("platforms",[slug]);if(error)throw error;let sent=0,expired=0;const payload=JSON.stringify({title:`🎁 ${game.title} está grátis!`,body:`De ${new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(game.original_price)} por R$ 0 na ${game.store}.`,url:game.claim_url,gameId:game.id});await Promise.all((data||[]).map(async sub=>{try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},payload,{TTL:86400,urgency:"high"});sent++}catch(error){const status=(error as {statusCode?:number}).statusCode;if(status===404||status===410){expired++;await db.from("push_subscriptions").update({active:false,updated_at:new Date().toISOString()}).eq("id",sub.id);}}}));return{sent,expired,total:data?.length||0}}
