"use client";
import Image from "next/image";
import Link from "next/link";
import {ArrowLeft,ArrowUpRight,Bookmark,Check,Monitor,Share2,Store} from "lucide-react";
import {useEffect,useState} from "react";
import type {Deal,SteamGameDetails} from "@/lib/deals";
import {SiteHeader} from "./site-header";
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export function DealDetails({deal,details}:{deal:Deal;details:SteamGameDetails}){
 const[saved,setSaved]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{try{setSaved((JSON.parse(localStorage.getItem("triobrabo:deal-wishlist")||"[]") as number[]).includes(deal.appId))}catch{}})},[deal.appId]);
 const toggle=()=>{const current=JSON.parse(localStorage.getItem("triobrabo:deal-wishlist")||"[]") as number[];const next=current.includes(deal.appId)?current.filter(id=>id!==deal.appId):[...current,deal.appId];localStorage.setItem("triobrabo:deal-wishlist",JSON.stringify(next));setSaved(next.includes(deal.appId))};
 return <><SiteHeader/><main className="deal-detail"><Link className="back-link" href="/ofertas"><ArrowLeft/> Voltar às ofertas</Link><section className="detail-hero"><div><p className="eyebrow"><Store/> Oferta na {deal.store}</p><h1>{details.name}</h1><p>{details.shortDescription}</p><div className="detail-tags">{details.genres.map(item=><span key={item}>{item}</span>)}</div><div className="detail-price"><s>{brl.format(deal.originalPrice)}</s><strong>{brl.format(deal.salePrice)}</strong><b>-{deal.discount}%</b></div><div className="detail-actions"><a href={deal.url} target="_blank" rel="noreferrer">Comprar na {deal.store}<ArrowUpRight/></a><button onClick={toggle}><Bookmark/>{saved?"Salvo":"Salvar"}</button><button onClick={()=>navigator.share?.({title:details.name,text:"Olha essa oferta no TrioBrabo!",url:window.location.href})}><Share2/>Compartilhar</button></div></div><Image src={details.headerImage} alt={`Capa de ${details.name}`} width={920} height={430} priority/></section><section className="offer-compare"><div><p className="eyebrow"><Check/> Onde comprar</p><h2>Ofertas encontradas</h2></div><article><Store/><div><strong>{deal.store}</strong><span>Ativação: {deal.activation}</span></div><s>{brl.format(deal.originalPrice)}</s><b>{brl.format(deal.salePrice)}</b><a href={deal.url} target="_blank" rel="noreferrer">Ir à loja <ArrowUpRight/></a></article><small>Novas lojas aparecerão aqui somente quando houver preço e disponibilidade confirmados.</small></section>{details.screenshots.length?<section className="screenshots"><h2>Imagens do jogo</h2><div>{details.screenshots.map((src,index)=><Image key={src} src={src} alt={`${details.name}, imagem ${index+1}`} width={600} height={338}/>)}</div></section>:null}<section className="game-info"><div><Monitor/><h2>Compatibilidade</h2><p>{details.platforms.join(", ")||"Windows"}</p></div><div><h2>Estúdio</h2><p>{details.developers.join(", ")||details.publishers.join(", ")}</p></div><div><h2>Requisitos mínimos</h2><p>{details.requirements}</p></div></section></main></>;
}
