"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Bookmark,ChevronLeft,ChevronRight,Clock3,Gamepad2,Search,SlidersHorizontal,Sparkles } from "lucide-react";
import type { Game } from "@/lib/types";
import { hoursLeft,money } from "@/lib/games";
import { getSupabase } from "@/lib/supabase";
import { SiteHeader } from "./site-header";
import { IntroSplash } from "./intro-splash";

function GameCard({game,saved,toggle}:{game:Game;saved:boolean;toggle:(id:string)=>void}){return <article className="card"><div className="cover" style={{backgroundImage:`url(${game.image_url})`}}><span>{game.store}</span><button aria-label={`Salvar ${game.title}`} className={saved?"saved":""} onClick={()=>toggle(game.id)}><Bookmark size={18}/></button></div><div className="card-body"><div className="tags">{game.genres.map(x=><span key={x}>{x}</span>)}</div><h3>{game.title}</h3><p>{game.description}</p><div className="price"><div><strong>Grátis</strong><s>{money(game.original_price)}</s></div><span><Clock3 size={15}/> {hoursLeft(game.ends_at)}h restantes</span></div><a href={game.claim_url} target="_blank" rel="noreferrer">Resgatar agora <ChevronRight size={17}/></a></div></article>}

export function GameBrowser({games}:{games:Game[]}){
 const [liveGames,setLiveGames]=useState(games);const [query,setQuery]=useState("");const [store,setStore]=useState("Todas");const [saved,setSaved]=useState<string[]>([]);const [onlySaved,setOnlySaved]=useState(false);const [slide,setSlide]=useState(0);const [paused,setPaused]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{setSaved(JSON.parse(localStorage.getItem("freedrop:saved")||"[]"));setOnlySaved(new URLSearchParams(window.location.search).get("salvos")==="1")});},[]);
 useEffect(()=>{const db=getSupabase();if(!db)return;let active=true;const refresh=async()=>{const{data}=await db.from("games").select("*").eq("is_active",true).order("featured",{ascending:false}).order("ends_at");if(active&&data?.length)setLiveGames(data)};const channel=db.channel("live-free-games").on("postgres_changes",{event:"*",schema:"public",table:"games"},refresh).subscribe();const timer=window.setInterval(refresh,60000);const onVisible=()=>{if(document.visibilityState==="visible")void refresh()};document.addEventListener("visibilitychange",onVisible);return()=>{active=false;window.clearInterval(timer);document.removeEventListener("visibilitychange",onVisible);void db.removeChannel(channel)}},[]);
 const spotlightGames=useMemo(()=>{const primary=liveGames.filter(g=>g.store==="Steam"||g.store==="Epic Games");const highResolution=primary.filter(g=>!g.image_url.includes("gamerpower.com/offers/"));return highResolution.length?highResolution:primary},[liveGames]);
 useEffect(()=>{if(paused||spotlightGames.length<2)return;const timer=setInterval(()=>setSlide(v=>(v+1)%spotlightGames.length),6500);return()=>clearInterval(timer)},[paused,spotlightGames.length]);
 const toggle=(id:string)=>setSaved(v=>{const n=v.includes(id)?v.filter(x=>x!==id):[...v,id];localStorage.setItem("freedrop:saved",JSON.stringify(n));return n});
 const stores=["Todas",...Array.from(new Set(liveGames.map(g=>g.store)))];
 const introImages=useMemo(()=>liveGames.map(game=>game.image_url),[liveGames]);
 const shown=useMemo(()=>liveGames.filter(g=>(store==="Todas"||g.store===store)&&(!query||`${g.title} ${g.genres.join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(!onlySaved||saved.includes(g.id))),[liveGames,store,query,onlySaved,saved]);
 const featured=spotlightGames[slide%Math.max(1,spotlightGames.length)];const highlights=[...spotlightGames].sort((a,b)=>+new Date(a.ends_at)-+new Date(b.ends_at));
 return <><IntroSplash images={introImages}/><SiteHeader saved={saved.length} onSaved={()=>setOnlySaved(v=>!v)}/><main>
  {featured&&<section className="showcase" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} style={{backgroundImage:`linear-gradient(90deg,rgba(6,7,10,.98) 12%,rgba(6,7,10,.66) 54%,rgba(6,7,10,.1)),url(${featured.image_url})`}}><div className="showcase-content" key={featured.id}><p className="eyebrow"><Sparkles size={15}/> Grátis agora em {featured.store}</p><h1>{featured.title}</h1><p>{featured.description}</p><div className="showcase-price"><strong>R$ 0</strong><s>{money(featured.original_price)}</s><span><Clock3 size={15}/>{hoursLeft(featured.ends_at)}h restantes</span></div><div className="showcase-actions"><a className="primary" href={featured.claim_url} target="_blank" rel="noreferrer">Resgatar agora <ChevronRight/></a><button onClick={()=>toggle(featured.id)}><Bookmark/> {saved.includes(featured.id)?"Salvo":"Salvar"}</button></div></div><div className="carousel-controls"><button aria-label="Anterior" onClick={()=>setSlide(v=>(v-1+spotlightGames.length)%spotlightGames.length)}><ChevronLeft/></button><div>{spotlightGames.map((g,i)=><button aria-label={`Ver ${g.title}`} key={g.id} className={i===slide?"current":""} onClick={()=>setSlide(i)}/>)}</div><button aria-label="Próximo" onClick={()=>setSlide(v=>(v+1)%spotlightGames.length)}><ChevronRight/></button></div></section>}
  <section className="quick-stats"><div><strong>{liveGames.length}</strong><span>drops ativos</span></div><div><strong>{money(liveGames.reduce((n,g)=>n+g.original_price,0))}</strong><span>economia disponível</span></div><Link href="/plataformas"><strong>20</strong><span>fontes no radar →</span></Link></section>
  <section className="rails"><div className="rail-heading"><div><p>Destaques principais</p><h2>Steam e Epic Games</h2></div></div><div className="rail">{highlights.map(g=><GameCard key={`highlight-${g.id}`} game={g} saved={saved.includes(g.id)} toggle={toggle}/>)}</div></section>
  <section id="jogos" className="catalog"><div className="section-title"><div><p>Sem deixar nada de fora</p><h2>Todos os jogos grátis</h2></div><span>{shown.length} ofertas</span></div><div className="toolbar"><label><Search/><input aria-label="Buscar jogos" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar jogo ou gênero..."/></label><div className="pills"><SlidersHorizontal/>{stores.map(s=><button className={store===s?"selected":""} onClick={()=>setStore(s)} key={s}>{s}</button>)}</div></div><div className="grid">{shown.map(g=><GameCard key={g.id} game={g} saved={saved.includes(g.id)} toggle={toggle}/>)}</div>{!shown.length&&<div className="empty"><Gamepad2/><h3>Nenhuma oferta encontrada</h3><p>Tente outro termo ou limpe os filtros.</p></div>}</section>
 </main></>;
}
