alter table public.games drop constraint if exists games_store_check;
create table if not exists public.platforms (slug text primary key,name text not null unique,kind text not null check (kind in ('Loja','Assinatura','Giveaway','Free-to-play')),website_url text not null,featured boolean not null default false,requires_subscription boolean not null default false,note text not null default '',active boolean not null default true,sort_order integer not null default 100,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.platforms enable row level security;
revoke all on table public.platforms from anon, authenticated;
grant select on table public.platforms to anon, authenticated;
create policy "active platforms are public" on public.platforms for select to anon, authenticated using (active);
insert into public.platforms (slug,name,kind,website_url,featured,requires_subscription,note,sort_order) values
('epic-games','Epic Games','Loja','https://store.epicgames.com/free-games',true,false,'Jogos semanais para ficar para sempre',1),('steam','Steam','Loja','https://store.steampowered.com/search/?maxprice=free',true,false,'Promoções free-to-keep, fins de semana e F2P',2),('gog','GOG','Loja','https://www.gog.com/',false,false,'Giveaways ocasionais e jogos sem DRM',3),('prime-gaming','Prime Gaming','Assinatura','https://gaming.amazon.com/',false,true,'Jogos mensais para assinantes Amazon Prime',4),('itch-io','itch.io','Loja','https://itch.io/games/free',false,false,'Grande catálogo indie gratuito e promoções',5),('indiegala','IndieGala','Giveaway','https://freebies.indiegala.com/',false,false,'Freebies DRM-free e chaves promocionais',6),('fanatical','Fanatical','Giveaway','https://www.fanatical.com/',false,false,'Giveaways ocasionais de chaves para PC',7),('humble-bundle','Humble Bundle','Giveaway','https://www.humblebundle.com/',false,false,'Giveaways e campanhas promocionais ocasionais',8),('ubisoft-connect','Ubisoft Connect','Loja','https://store.ubisoft.com/free-games',false,false,'Free weekends, demos e ofertas gratuitas',9),('ea-app','EA app','Loja','https://www.ea.com/ea-app',false,false,'Jogos gratuitos, testes e fins de semana',10),('xbox-pc','Xbox / Microsoft Store','Loja','https://www.xbox.com/pc-gaming',false,false,'Jogos F2P e promoções para PC',11),('battle-net','Battle.net','Free-to-play','https://www.blizzard.com/apps/battle.net/desktop',false,false,'Catálogo gratuito da Blizzard',12),('riot-games','Riot Games','Free-to-play','https://www.riotgames.com/',false,false,'Jogos competitivos gratuitos para PC',13),('hoyoverse','HoYoverse','Free-to-play','https://www.hoyoverse.com/',false,false,'RPGs e aventuras gratuitos para PC',14),('wargaming','Wargaming.net','Free-to-play','https://wargaming.net/',false,false,'Jogos online gratuitos e eventos',15),('gaijin','Gaijin.net','Free-to-play','https://gaijin.net/',false,false,'Jogos online gratuitos para PC',16),('ncsoft','NCSoft / PURPLE','Free-to-play','https://www.plaync.com/',false,false,'MMOs gratuitos e campanhas',17),('pearl-abyss','Pearl Abyss','Free-to-play','https://www.pearlabyss.com/',false,false,'MMOs e períodos promocionais',18),('alienware-arena','Alienware Arena','Giveaway','https://www.alienwarearena.com/giveaways',false,false,'Chaves, sorteios e recompensas para PC',19),('steelseries-gg','SteelSeries GG','Giveaway','https://steelseries.com/gg/collectors',false,false,'Chaves e itens promocionais limitados',20)
on conflict (slug) do update set name=excluded.name,kind=excluded.kind,website_url=excluded.website_url,featured=excluded.featured,requires_subscription=excluded.requires_subscription,note=excluded.note,sort_order=excluded.sort_order,updated_at=now();
